debug_mode: False
use_log: False
robot_id: 0

role_info:
    is_client: False
    id: 'edge-01'

network_info:
    ip: '127.0.0.1'

    target_info:
        ip: '127.0.0.1'

message_info:
    msg:
        is_tcp: True
        port: 21000
    odm:
        is_tcp: True
        port: 22000
    pcd:
        is_tcp: True
        port: 23000
    cmd:
        is_tcp: True
        port: 24000
    img:
        is_tcp: True
        port: 25000
    rtk:
        is_tcp: True
        port: 26000
    ldr:
        is_tcp: True
        port: 27000

